[book]
authors = ["Project Liberty Institute"]
language = "en"
multilingual = false
src = "pages"
title = "DSNP Specification"

[output.html]
no-section-label = true
copy-fonts = false # Switched to custom fonts
site-url = "/pages/"
git-repository-url = "https://github.com/LibertyDSNP/spec"
edit-url-template = "https://github.com/LibertyDSNP/spec/blob/main/{path}"
preferred-dark-theme = "coal"

# https://github.com/Michael-F-Bryan/mdbook-linkcheck
[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
exclude = ['en\.bitcoin\.it', 'github\.com/LibertyDSNP/spec', 'w3\.org']

[output.html.fold]
enable = true

# https://github.com/jonahgoldwastaken/mdbook-external-links
# [preprocessor.external-links]
