[book]
authors = ["Unfinished"]
language = "en"
multilingual = false
src = "pages"
title = "DSNP Specification"

[build]
create-missing = false

[output.html]
no-section-label = true
git-repository-url = "https://github.com/LibertyDSNP/spec"
edit-url-template = "https://github.com/LibertyDSNP/spec/blob/main/{path}"

[output.html.fold]
enable = true