name: "Install mdBook with Plugins"
description: "Shared action steps to install mdBook with required plugins"
inputs:
  token:
    description: "Pass through for secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup mdBook 📚
      run: cargo install mdbook mdbook-linkcheck mdbook-external-links
    - name: Show mdbook version
      shell: bash
      run: mdbook --version
    - name: Show linkchecker version
      shell: bash
      run: mdbook-linkcheck --version
